<?php

/**
 * Add jquery and theme level scripts
 */
function matt_page_alter(&$page) {
  $page['#attached']['library'][] = 'matt/matt-corescripts';
}

/**
 * Implements hook_preprocess_node
 */
function matt_preprocess_node(&$vars) {
  if ($vars['node']->getType() === 'article') {
    $unformatted_date = $vars['node']->getCreatedTime();
    $vars['date'] = format_date($unformatted_date, 'custom', 'M d, Y');
  }
}
