# Base types provided by Drupal core.

# Read https://drupal.org/node/1905070 for more details about configuration
# schema, types and type resolution.

# Undefined type used by the system to assign to elements at any level where
# configuration schema is not defined. Using explicitly has the same effect as
# not defining schema, so there is no point in doing that.
undefined:
  label: 'Undefined'
  class: '\Drupal\Core\Config\Schema\Undefined'

# Explicit type to use when no data typing is possible. Instead of using this
# type, we strongly suggest you use configuration structures that can be
# described with other structural elements of schema, and describe your schema
# with those elements.
ignore:
  label: 'Ignore'
  class: '\Drupal\Core\Config\Schema\Ignore'

# Basic scalar data types from typed data.
boolean:
  label: 'Boolean'
  class: '\Drupal\Core\TypedData\Plugin\DataType\Boolean'
email:
  label: 'Email'
  class: '\Drupal\Core\TypedData\Plugin\DataType\Email'
integer:
  label: 'Integer'
  class: '\Drupal\Core\TypedData\Plugin\DataType\Integer'
float:
  label: 'Float'
  class: '\Drupal\Core\TypedData\Plugin\DataType\Float'
string:
  label: 'String'
  class: '\Drupal\Core\TypedData\Plugin\DataType\String'
uri:
  label: 'Uri'
  class: '\Drupal\Core\TypedData\Plugin\DataType\Uri'

# Container data types for lists with known and unknown keys.
mapping:
  label: Mapping
  class: '\Drupal\Core\Config\Schema\Mapping'
  definition_class: '\Drupal\Core\TypedData\MapDataDefinition'
sequence:
  label: Sequence
  class: '\Drupal\Core\Config\Schema\Sequence'
  definition_class: '\Drupal\Core\TypedData\ListDataDefinition'

# Simple extended data types:

# Human readable string that must be plain text and editable with a text field.
label:
  type: string
  label: 'Label'
  translatable: true

# Internal Drupal path
path:
  type: string
  label: 'Path'

# Human readable string that can contain multiple lines of text or HTML.
text:
  type: string
  label: 'Text'
  translatable: true

# PHP Date format string that is translatable.
date_format:
  type: string
  label: 'Date format'
  translatable: true
  translation context: 'PHP date format'

# HTML color value.
color_hex:
  type: string
  label: 'Color'

# Complex extended data types:

# Mail text with subject and body parts.
mail:
  type: mapping
  label: 'Mail'
  mapping:
    subject:
      type: label
      label: 'Subject'
    body:
      type: text
      label: 'Body'

# Filter with module and status.
filter:
  type: mapping
  label: 'Filter'
  mapping:
    id:
      type: string
      label: 'ID'
    provider:
      type: string
      label: 'Provider'
    status:
      type: boolean
      label: 'Status'
    weight:
      type: integer
      label: 'Weight'
    settings:
      type: filter_settings.[%parent.id]

# System action configuration base.
action_configuration_default:
  type: sequence
  label: 'Action configuration'
  sequence:
    - type: string

theme_settings:
  type: mapping
  mapping:
    favicon:
      type: mapping
      label: 'Shortcut icon settings'
      mapping:
        mimetype:
          type: string
          label: 'MIME type'
        path:
          type: string
          label: 'Path'
        url:
          type: string
          label: 'URL'
        use_default:
          type: boolean
          label: 'Use the default shortcut icon supplied by the theme'
    features:
      type: mapping
      label: 'Optional features'
      mapping:
        comment_user_picture:
          type: boolean
          label: 'User pictures in comments'
        comment_user_verification:
          type: boolean
          label: 'User verification status in comments'
        favicon:
          type: boolean
          label: 'Shortcut icon'
        logo:
          type: boolean
          label: 'Logo'
        name:
          type: boolean
          label: 'Site name'
        node_user_picture:
          type: boolean
          label: 'User pictures in posts'
        slogan:
          type: boolean
          label: 'Site slogan'
    logo:
      type: mapping
      label: 'Logo settings'
      mapping:
        path:
          type: string
          label: 'Logo path'
        url:
          type: uri
          label: 'URL'
        use_default:
          type: boolean
          label: 'Use default'

theme_breakpoints_default:
  type: sequence
  sequence:
    - type: string
      label: 'Breakpoint value'

views_field_bulk_form:
  type: views_field
  label: 'Bulk operation'
  mapping:
    action_title:
      type: label
      label: 'Action title'

# Array of routes with route_name and route_params keys.
route:
  type: mapping
  label: 'Route'
  mapping:
    route_name:
      type: string
      label: 'Route Name'
    route_params:
      type: sequence
      label: 'Route Params'
      sequence:
        - type: string
          label: 'Param'

# Config dependencies.
config_dependencies:
  type: mapping
  label: 'Configuration dependencies'
  mapping:
    entity:
      type: sequence
      label: 'Entity dependencies'
      sequence:
        - type: string
    module:
      type: sequence
      label: 'Module dependencies'
      sequence:
        - type: string
    theme:
      type: sequence
      label: 'Theme dependencies'
      sequence:
        - type: string

config_entity:
  type: mapping
  mapping:
    uuid:
      type: string
      label: 'UUID'
    langcode:
      type: string
      label: 'Default language'
    status:
      type: boolean
      label: 'Status'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'

block_settings:
  type: mapping
  label: 'Block settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Description'
    label_display:
      type: string
      label: 'Display title'
    cache:
      type: mapping
      label: 'Cache settings'
      mapping:
        max_age:
          type: integer
          label: 'Maximum age'
        contexts:
          type: sequence
          label: 'Vary by context'
          sequence:
            - type: string
              label: 'Context'
    status:
      type: boolean
      label: 'Status'
    info:
      type: label
      label: 'Admin info'
    view_mode:
      type: string
      label: 'View mode'
    visibility:
      type: sequence
      label: 'Visibility Conditions'
      sequence:
        - type: condition.plugin.[id]
          label: 'Visibility Condition'
    provider:
      type: string
      label: 'Provider'

condition.plugin:
  type: mapping
  label: 'Condition'
  mapping:
    id:
      type: string
      label: 'ID'
    negate:
      type: boolean
      label: 'Negate'
    uuid:
      type: string
      label: 'UUID'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        - type: string

display_variant.plugin:
  type: mapping
  label: 'Display variant'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
      label: 'UUID'

base_entity_reference_field_settings:
  type: mapping
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'
    target_bundle:
      type: string
      label: 'Bundle of item to reference'

field_config_base:
  type: config_entity
  mapping:
    id:
      type: string
      label: 'ID'
    field_name:
      type: string
      label: 'Field name'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Bundle'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Help text'
    required:
      type: boolean
      label: 'Required field'
    translatable:
      type: boolean
      label: 'Translatable'
    default_value:
      type: field.[%parent.field_type].value
    default_value_callback:
      type: string
      label: 'Default value callback'
    settings:
      type: field.[%parent.field_type].field_settings
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        - type: field_config.third_party.[%key]
    field_type:
      type: string
      label: 'Field type'

core.base_field_override.*.*.*:
  type: field_config_base
  label: 'Base field bundle override'

core.date_format.*:
  type: config_entity
  label: 'Date format'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    locked:
      type: boolean
      label: 'Locked'
    pattern:
      type: date_format
      label: 'PHP date format'
    langcode:
      type: string
      label: 'Default language'

# Schema for the String field type.

field.string.field_settings:
  type: sequence
  label: 'String settings'
  sequence:
    - type: string
      label: 'Setting'

field.string.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        value:
          type: string
          label: 'Value'

# Schema for the configuration files of the Boolean field type.

field.boolean.storage_settings:
  type: mapping
  label: 'Boolean settings'
  mapping:
    on_label:
      type: string
      label: 'On label'
    off_label:
      type: string
      label: 'Off label'

field.boolean.field_settings:
  label: 'Boolean settings'
  type: mapping
  mapping: {  }

field.boolean.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        value:
          type: integer
          label: 'Value'

# Schema for the configuration files of the Email field type.

field.email.storage_settings:
  type: sequence
  label: 'Email settings'
  sequence:
    - type: string

field.email.field_settings:
  type: sequence
  label: 'Email settings'
  sequence:
    - type: string
      label: 'Setting'

field.email.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        value:
          type: email
          label: 'Value'

# Schema for configuration files of a numeric field types.

field.integer.storage_settings:
  type: sequence
  label: 'Integer settings'
  sequence:
    - type: string
      label: 'setting'

field.integer.field_settings:
  type: mapping
  label: 'Integer'
  mapping:
    min:
      type: integer
      label: 'Minimum'
    max:
      type: integer
      label: 'Maximum'
    prefix:
      type: string
      label: 'Prefix'
    suffix:
      type: string
      label: 'Suffix'

field.integer.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default value'
      mapping:
        value:
          type: integer
          label: 'Value'

field.decimal.storage_settings:
  type: mapping
  label: 'Decimal settings'
  mapping:
    precision:
      type: integer
      label: 'Precision'
    scale:
      type: integer
      label: 'Scale'

field.decimal.field_settings:
  type: mapping
  label: 'Decimal'
  mapping:
    min:
      type: float
      label: 'Minimum'
    max:
      type: float
      label: 'Maximum'
    prefix:
      type: string
      label: 'Prefix'
    suffix:
      type: string
      label: 'Suffix'

field.decimal.value:
   type: sequence
   label: 'Default value'
   sequence:
     - type: mapping
       label: 'Default value'
       mapping:
         value:
           type: float
           label: 'Value'

field.float.storage_settings:
  type: sequence
  label: 'Float settings'
  sequence:
    - type: string
      label: 'setting'

field.float.field_settings:
  type: mapping
  label: 'Float'
  mapping:
    min:
      type: float
      label: 'Minimum'
    max:
      type: float
      label: 'Maximum'
    prefix:
      type: string
      label: 'Prefix'
    suffix:
      type: string
      label: 'Suffix'

field.float.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default value'
      mapping:
        value:
          type: float
          label: 'Value'
