core.extension:
  type: mapping
  label: 'Extension settings'
  mapping:
    module:
      type: sequence
      label: 'Enabled modules'
      sequence:
        - type: integer
          label: 'Weight'
    theme:
      type: sequence
      label: 'Installed themes'
      sequence:
        - type: integer
          label: 'Weight'
